---

- name: Deploy {{ app_name }} playbook
  become: true
  hosts: localhost
  vars:
    password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62323035343666363835393538633937663861626433363534303661313135663165376339396238
          3233326135393863353438373564346436323339613437340a396335326332383037656465643261
          34616436376663386632373163396634666664306233646263363037336161333830366162623163
          6131643964393863610a303961666564306365306262663430646365323761363766336165336234
          6337
  tasks:

    - name: Clean  directory for existing files
      file:
        state: absent
        path: "/opt/{{ app_name }}"
        
    - name: Clean  directory for existing files
      file:
        state: absent
        path: "/tmp/{{ app_name }}"

    - name: create application directory if doesnot exist
      file:
        state: directory
        path: "/opt/{{ app_name }}/"
        owner: root
        group: root
        
    - name: create application directory in tmp if doesnot exist
      file:
        state: directory
        path: "/tmp/{{ app_name }}/"
        owner: root
        group: root    
  
    #- name: Fetch jar file
     # get_url:
      #  url: http://18.156.34.249:8081/repository/maven-snapshots/com/strikers/mediclaim/0.0.1-SNAPSHOT/mediclaim-0.0.1-20210629.103925-6.jar
       # dest: "/tmp/{{ app_name }}/"
       # url_username: admin
       # url_password: password
        
    - name: fetch from nexus
      maven_artifact:
        group_id: com.strikers
        username: admin
        password: "{{ password }}"
        artifact_id: mediclaim
        extension: jar
        repository_url: 'http://52.237.88.98:8081/repository/maven-snapshots'
        dest: /tmp/{{ app_name }}/{{ app_name }}.jar
        version: latest

    - name: Copy jar file to application directory
      copy:
        src: "/tmp/{{ app_name }}/{{ app_name }}.jar"
        dest: "/opt/{{ app_name }}/"
        mode: 0744
        
      
    - name: Restart service 
      service:
        state: restarted
        name: mediclaim
      
            
